### ISSUE TITLE
Update to API v. 17?

### ISSUE THREAD

**Issue by toovy** [typewig/bitwig-api-ts-stubs#4]
Hi @joslarson, I started out playing with Bitwigs API, knowing TypeScript I found this project and saw the great potential. I can see, that the supported API version is 12 (package.json) and now we got 17. I cloned the repo, changed to 17 and ran `npm run build`, but the check command throws some errors. Do you have any plans to come back to this project?

**Comment by toovy** [comment]
Oh, I just saw the PR https://github.com/taktiljs/typed-bitwig-api/pull/3/commits/b6369d59ef88cfff05ae3a6197e25dda553d6924 that solves issues for v16 and seems to also work for v17. I did the changes manually, but if you would accept PRs at least, it would help a lot. Thanks!

**Comment by joslarson** [comment]
Hey there! I'm very much still actively using and maintaining this, it's just easy to forget to update/publish new versions of the API if I'm not using new API features yet. I made a note on PR #3, but once that's merged I'll publish versions 13-17. Thanks for the reminder :) I'll close this with a note once v17 is published

**Comment by joslarson** [comment]
I just published v17, let me know if you have any issues with that, thanks again

**Comment by wpostma** [comment]
The RELEASE file for v1.0 is not even a compiled release? Why is that?
Here's a compile for v1.0
[LaunchpadProMk3.zip](https://github.com/joslarson/typed-bitwig-api/files/10145814/LaunchpadProMk3.zip)
